# Generated by Django 5.2.5 on 2025-09-02 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('doctor', models.CharField(editable=False, max_length=20, unique=True)),
                ('room_no', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=15)),
                ('appointment_type', models.CharField(choices=[('checkup', 'Check Up'), ('followup', 'Follow Up'), ('emergency', 'Emergency')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('normal', 'Normal'), ('severe', 'Severe')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='HMS_backend.department')),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['-created_at'],
            },
        ),
    ]
