# Generated by Django 5.2.5 on 2025-09-26 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin')], max_length=50)),
                ('module', models.CharField(choices=[('viewPatients', 'View Patients'), ('editPatients', 'Edit Patients'), ('generateBills', 'Generate Bills'), ('approveInsurance', 'Approve Insurance'), ('manageAppointments', 'Manage Appointments'), ('manageInventory', 'Manage Inventory'), ('ambulance', 'Ambulance')], max_length=100)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('role', 'module')},
            },
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_logs', models.BooleanField(default=True)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('login_alerts', models.BooleanField(default=False)),
                ('last_password_change', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_settings', to='HMS_backend.staff')),
            ],
        ),
    ]
