# Generated by Django 5.2.5 on 2025-09-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0004_bloodgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Eligible', 'Eligible'), ('Not Eligible', 'Not Eligible')], default='Not Eligible', max_length=20)),
                ('added_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'donors',
                'ordering': ['donor_name'],
            },
        ),
    ]
