# Generated by Django 5.2.5 on 2025-10-22 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0004_alter_securitysettings_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(max_length=50)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('allocation_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HMS_backend.department')),
                ('lab_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_allocations', to='HMS_backend.labreport')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_allocations', to='HMS_backend.patient')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_allocations', to='HMS_backend.staff')),
            ],
            options={
                'db_table': 'medicine_allocations',
                'ordering': ['-allocation_date'],
            },
        ),
    ]
