# Generated by Django 5.2.5 on 2025-10-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0005_medicineallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='item_code',
            field=models.CharField(default='TEMP001', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='rack_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='shelf_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
