# Generated by Django 5.2.5 on 2025-10-31 12:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0006_stock_item_code_stock_rack_no_stock_shelf_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='address',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='doctor',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='email',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='generated_invoices/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='phone',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='invoices',
        ),
    ]
