# Generated by Django 5.2.5 on 2025-09-22 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0006_labreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='labreport',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='labreport',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='labreport',
            name='patient',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='HMS_backend.patient'),
            preserve_default='True',
        ),
        migrations.AlterModelTable(
            name='labreport',
            table='lab_reports',
        ),
    ]
