# Generated by Django 5.2.5 on 2025-11-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0007_invoice_address_invoice_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bed_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
