# Generated by Django 5.2.5 on 2025-09-22 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0007_alter_labreport_options_remove_labreport_patient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='HMS_backend.patient'),
        ),
    ]
