# Generated by Django 5.2.5 on 2025-09-22 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0008_alter_labreport_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedGroup', models.CharField(max_length=100, unique=True)),
                ('capacity', models.IntegerField()),
                ('occupied', models.IntegerField(default=0)),
                ('unoccupied', models.IntegerField(default=0)),
                ('status', models.CharField(default='Available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period', models.CharField(max_length=20)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='HMS_backend.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='HMS_backend.staff')),
            ],
            options={
                'db_table': 'staff_management',
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.IntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
                ('bed_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='HMS_backend.bedgroup')),
            ],
            options={
                'unique_together': {('bed_number', 'bed_group')},
            },
        ),
    ]
