# Generated by Django 5.2.5 on 2025-11-04 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0008_alter_bed_bed_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beds', to='HMS_backend.patient'),
        ),
    ]
