# Generated by Django 5.2.5 on 2025-09-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0009_bedgroup_payroll_staff_management_bed'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff',
            table='staff',
        ),
    ]
