# Generated by Django 5.2.5 on 2025-11-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0010_patient_discharge_date_alter_patient_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bed',
            options={'ordering': ['bed_group', 'bed_number']},
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bedgroup',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
