# Generated by Django 5.2.5 on 2025-09-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0010_alter_staff_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('vendor_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('outofstock', 'Out of Stock')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stock',
                'unique_together': {('product_name', 'batch_number', 'vendor_id')},
            },
        ),
    ]
