# Generated by Django 5.2.5 on 2025-11-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0011_alter_bed_options_alter_bed_bed_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineallocation',
            name='lab_report',
        ),
        migrations.AddField(
            model_name='medicineallocation',
            name='lab_reports',
            field=models.ManyToManyField(blank=True, related_name='medicine_allocations', to='HMS_backend.labreport'),
        ),
    ]
