# Generated by Django 5.2.5 on 2025-09-23 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0011_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('in_service', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ambulance_units',
                'ordering': ['unit_number'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_id', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_id', models.CharField(max_length=50, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('dispatcher', models.CharField(max_length=150)),
                ('call_type', models.CharField(choices=[('Emergency', 'Emergency'), ('Non-Emergency', 'Non-Emergency'), ('Transfer', 'Transfer')], default='Emergency', max_length=30)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('En Route', 'En Route'), ('Standby', 'Standby'), ('Cancelled', 'Cancelled')], default='Standby', max_length=30)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='HMS_backend.ambulanceunit')),
            ],
            options={
                'db_table': 'ambulance_dispatches',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=50, unique=True)),
                ('crew', models.TextField(blank=True, null=True)),
                ('patient_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pickup_location', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('mileage', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('En Route', 'En Route'), ('Standby', 'Standby'), ('Cancelled', 'Cancelled')], default='Standby', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='HMS_backend.dispatch')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='HMS_backend.ambulanceunit')),
            ],
            options={
                'db_table': 'ambulance_trips',
                'ordering': ['-created_at'],
            },
        ),
    ]
