# Generated by Django 5.2.5 on 2025-11-10 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0012_remove_medicineallocation_lab_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineallocation',
            name='lab_reports',
        ),
        migrations.AddField(
            model_name='medicineallocation',
            name='lab_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_allocations', to='HMS_backend.labreport'),
        ),
    ]
