# Generated by Django 5.2.5 on 2025-11-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0013_remove_medicineallocation_lab_reports_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineallocation',
            name='lab_report',
        ),
        migrations.AddField(
            model_name='medicineallocation',
            name='lab_report_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
