# Generated by Django 5.2.5 on 2025-11-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0014_remove_medicineallocation_lab_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='dispatch_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
