# Generated by Django 5.2.5 on 2025-11-17 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0015_alter_dispatch_dispatch_id_alter_trip_trip_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='trip',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_trips', to='HMS_backend.patient'),
        ),
    ]
