# Generated by Django 5.2.5 on 2026-02-19 09:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0024_ambulanceunit_contact_number_ambulanceunit_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hospitalinvoicehistory',
            name='tax_percent',
        ),
        migrations.AddField(
            model_name='hospitalinvoicehistory',
            name='cgst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='hospitalinvoicehistory',
            name='cgst_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='hospitalinvoicehistory',
            name='consolidate_source_ids',
            field=models.TextField(blank=True, help_text='JSON array of invoice IDs included in this consolidate invoice', null=True),
        ),
        migrations.AddField(
            model_name='hospitalinvoicehistory',
            name='consolidated_date',
            field=models.DateField(blank=True, help_text='Date when this invoice was consolidated', null=True),
        ),
        migrations.AddField(
            model_name='hospitalinvoicehistory',
            name='consolidated_invoice_id',
            field=models.CharField(blank=True, help_text='ID of the consolidate invoice that includes this invoice', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospitalinvoicehistory',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='hospitalinvoicehistory',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='hospitalinvoicehistory',
            name='due_date',
            field=models.DateField(blank=True, help_text='Due date for pending amount (partial payments)', null=True),
        ),
        migrations.AddField(
            model_name='hospitalinvoicehistory',
            name='is_consolidated',
            field=models.BooleanField(default=False, help_text='Whether this invoice has been included in a consolidate invoice'),
        ),
        migrations.AddField(
            model_name='hospitalinvoicehistory',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid so far (for partial payments)', max_digits=12),
        ),
        migrations.AddField(
            model_name='hospitalinvoicehistory',
            name='payment_remarks',
            field=models.TextField(blank=True, help_text='Remarks for partial payment', null=True),
        ),
        migrations.AddField(
            model_name='hospitalinvoicehistory',
            name='payment_type',
            field=models.CharField(choices=[('Full Payment', 'Full Payment'), ('Partial Payment', 'Partial Payment'), ('Insurance', 'Insurance'), ('Credit', 'Credit'), ('Consolidate', 'Consolidate')], default='Full Payment', max_length=20),
        ),
        migrations.AddField(
            model_name='hospitalinvoicehistory',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining amount to be paid', max_digits=12),
        ),
        migrations.AddField(
            model_name='hospitalinvoicehistory',
            name='sgst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='hospitalinvoicehistory',
            name='sgst_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='hospitalinvoicehistory',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='hospitalinvoicehistory',
            name='tax_net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='hospitalinvoicehistory',
            name='total_tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='hospitalinvoicehistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='treatmentcharge',
            name='billed_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount already billed/paid', max_digits=12),
        ),
        migrations.AddField(
            model_name='treatmentcharge',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='treatmentcharge',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount still to be billed', max_digits=12),
        ),
        migrations.AddField(
            model_name='treatmentcharge',
            name='tax_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalinvoicehistory',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Pending', 'Pending'), ('Partially Paid', 'Partially Paid')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='treatmentcharge',
            name='hospital_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_charges', to='HMS_backend.hospitalinvoicehistory'),
        ),
        migrations.AlterField(
            model_name='treatmentcharge',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_BILLED', 'Partially Billed'), ('BILLED', 'Billed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='PartialPaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.PositiveIntegerField(help_text='Payment sequence number')),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_payments', to='HMS_backend.hospitalinvoicehistory')),
            ],
            options={
                'verbose_name': 'Partial Payment',
                'verbose_name_plural': 'Partial Payments',
                'db_table': 'partial_payment_history',
                'ordering': ['payment_number'],
            },
        ),
    ]
