# Generated by Django 5.2.5 on 2026-02-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0025_charge_remove_hospitalinvoicehistory_tax_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='charge_scope',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SPECIFIC', 'Specific')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='hospitalinvoiceitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='hospitalinvoiceitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='hospitalinvoiceitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='hospitalinvoiceitem',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(default='Available', max_length=50),
        ),
    ]
