# Generated by Django 5.2.5 on 2026-02-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0026_charge_charge_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
