# Generated by Django 5.2.5 on 2026-03-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0027_patienthistory_admission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='tax_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='current_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
