# Generated by Django 5.2.5 on 2026-03-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0028_charge_tax_percent_patienthistory_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalinvoicehistory',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
