# Generated by Django 5.2.5 on 2026-03-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0029_alter_hospitalinvoicehistory_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
